version: "3"

services:
  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
  db:
    image: postgres
    ports:
    - "5555:5432"
    environment:
    - POSTGRES_PASSWORD=password
    - POSTGRES_USER=admin

  vue:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    depends_on:
      - django
