version: "3"

services:
  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db
    # restart: on-failure
  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5555:5432"

  vue:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      # node_modules needs its seperate volumn
      - /app/node_modules
    depends_on:
      - django
volumes:
  postgres_data:
