version: "3"

services:
  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
     sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file: backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: backend/.env
    ports:
    - "5555:5432"
    environment:
    - POSTGRES_PASSWORD=password
    - POSTGRES_USER=admin

  vue:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    depends_on:
      - django
volumes:
  postgres_data:
